# Application Settings
spring.application.name=candle-landing-page
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri= mongodb://localhost:27017/candle_academy
# spring.data.mongodb.host=localhost
# spring.data.mongodb.port=27017
# spring.data.mongodb.database=candle_academy

# Razorpay Configuration (Placeholders for future setup)
 razorpay.key.id=${RAZORPAY_KEY_ID}
 razorpay.key.secret=${RAZORPAY_KEY_SECRET}


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yourcompany@gmail.com
spring.mail.password=YOUR_APP_PASSWORD

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true