# Application Settings
spring.application.name=candle-landing-page
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri= mongodb://localhost:27017/candle_academy
# spring.data.mongodb.host=localhost
# spring.data.mongodb.port=27017
# spring.data.mongodb.database=candle_academy

# Razorpay Configuration (Placeholders for future setup)
# razorpay.key.id=
# razorpay.key.secret=
