# Application Settings
spring.application.name=candle-landing-page
server.port=${PORT:8080}

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI}

# Razorpay Configuration (Placeholders for future setup)
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true